version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/project
    ports:
      - 8011:8011
    env_file:
      - .env
    restart: always
